function F3u= F3u(gup,glow,u,v,phi,rho)
global  We 
F3u= -u.*gradx(averx_m(u))...
           -averx_m(averyDtoN(v)).*gradyDtoN([gup; averyNtoDin(u); glow])...
           -(1/We)*averx_m(phi).*gradx_m(mu_phi(phi,rho))...
           -(1/We)*averx_m(rho).*gradx_m(mu_rho(phi,rho));
end
