function F3v= F3v(u,v,phi,rho)
global  We 
F3v= -averyNtoDin(averx(u)).*gradx(averx_m(v(2:end-1,:)))...
          -v(2:end-1,:).*gradyNtoDin(averyDtoN(v))...
         -(1/We)*averyNtoDin(phi).*gradyNtoDin(mu_phi(phi,rho))...
         -(1/We)*averyNtoDin(rho).*gradyNtoDin(mu_rho(phi,rho));
end
